"""G-code 生成(GRBL / Creality Falcon2)と、生成後の安全検証。

安全のための三段構え
    1. 生成前: 全座標(リードイン・待機位置を含む)が加工エリア内かを検査。
       1 点でも外れたら WorkAreaError(G-code は 1 行も返さない)
    2. 生成: ヘッダで G21 G90 G94 / M5 / S0 / 原点付近へ G0 S0。
       各輪郭は「G0 ... S0 → M4 S<p> → G1 ... → M5」。末尾は必ず M5
    3. 生成後: 出来上がったテキストを独立したパーサで読み直し、規則違反
       (G0 に S0 が無い、発振中の G0、M3 の使用、範囲外座標、末尾 M5 欠落など)
       があれば GcodeSafetyError。プレビューも同じパーサの結果から描く
       ので、「見た絵」と「流すコード」が食い違わない
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Iterable, Sequence

from .config import Machine
from .errors import GcodeSafetyError, WorkAreaError
from .geometry import Point
from .toolpath import CutPath, Plan

COORD_DECIMALS = 3
ALLOWED_G = {0, 1, 21, 90, 94}
ALLOWED_M = {4, 5, 8, 9}
PASS_MODES = ("path", "cycle")


def fmt(v: float) -> str:
    s = f"{round(v, COORD_DECIMALS):.{COORD_DECIMALS}f}"
    return "0.000" if s == "-0.000" else s


def rounded(v: float) -> float:
    return float(fmt(v))


def ascii_comment(text: str) -> str:
    """G-code のコメントは ASCII に限る(送信ソフトやファームが非 ASCII で誤動作しうる)。"""
    return "".join(ch if 32 <= ord(ch) < 127 and ch not in "()" else "?" for ch in text)


def power_to_s(percent: float, s_max: int, warnings: list[str] | None = None, where: str = "") -> int:
    """出力 % → S 値。0〜s_max にクランプする。"""
    s = round(percent / 100.0 * s_max)
    if s < 0 or s > s_max:
        clamped = min(max(s, 0), s_max)
        if warnings is not None:
            warnings.append(f"出力 {percent}% は範囲外のため S{clamped} にクランプしました {where}".rstrip())
        s = clamped
    return int(s)


# --------------------------------------------------------------------------
# 1. 加工エリア検査
# --------------------------------------------------------------------------

@dataclass
class AreaViolation:
    x: float
    y: float
    path_index: int | None
    description: str


def find_area_violations(paths: Sequence[CutPath], machine: Machine,
                         extra_points: Iterable[tuple[Point, str]] = ()) -> list[AreaViolation]:
    """0 <= X <= x_max, 0 <= Y <= y_max を外れる点を列挙する(G-code に書かれる桁で判定)。"""
    out = []

    def bad(x, y):
        x, y = rounded(x), rounded(y)
        return x < 0 or y < 0 or x > machine.x_max or y > machine.y_max

    for (x, y), desc in extra_points:
        if bad(x, y):
            out.append(AreaViolation(x, y, None, desc))
    for i, p in enumerate(paths):
        for x, y in p.points:
            if bad(x, y):
                out.append(AreaViolation(x, y, i, f"path #{i + 1} layer='{p.layer}' role={p.role} {p.source}"))
    return out


def check_work_area(paths: Sequence[CutPath], machine: Machine,
                    extra_points: Iterable[tuple[Point, str]] = ()) -> None:
    v = find_area_violations(paths, machine, extra_points)
    if not v:
        return
    lines = [f"加工エリア (0<=X<={machine.x_max}, 0<=Y<={machine.y_max}) の外の座標が {len(v)} 点あります。"
             "G-code は出力しません。"]
    seen = set()
    for a in v:
        if a.description in seen:
            continue
        seen.add(a.description)
        lines.append(f"  X={a.x:.3f} Y={a.y:.3f}  ← {a.description}")
        if len(seen) >= 10:
            lines.append("  ...")
            break
    xs = [a.x for a in v]
    ys = [a.y for a in v]
    lines.append(f"  範囲外の点の広がり: X {min(xs):.3f}〜{max(xs):.3f}, Y {min(ys):.3f}〜{max(ys):.3f}")
    lines.append("  対処: DXF の原点を見直すか、--align lower-left / --offset DX DY で配置してください")
    raise WorkAreaError("\n".join(lines))


# --------------------------------------------------------------------------
# 2. 生成
# --------------------------------------------------------------------------

@dataclass
class GcodeResult:
    text: str
    warnings: list[str] = field(default_factory=list)
    burns: int = 0  # M4〜M5 の区間の数(= 輪郭数 × パス回数)


def generate_gcode(plan: Plan, machine: Machine, *, pass_mode: str = "path",
                   meta: dict[str, str] | None = None) -> GcodeResult:
    """Plan から G-code を作る。エリア外の座標があれば WorkAreaError。

    pass_mode:
      "path"  … 1 本の輪郭を指定回数続けて切ってから次へ(既定)。
                穴が完全に抜けてから外形に移るので、内→外の順序が崩れない
      "cycle" … 全輪郭を 1 周ずつ切り、それを回数分繰り返す。
                材料が冷える時間ができるが、途中で部品が抜けると位置がずれる
    """
    if pass_mode not in PASS_MODES:
        raise ValueError(f"pass_mode は {PASS_MODES} のいずれか")
    park = (machine.park_x, machine.park_y)
    check_work_area(plan.paths, machine, [(park, "待機位置 park_x/park_y")])

    warnings: list[str] = []
    out: list[str] = []
    meta = meta or {}

    out.append("; Generated by laser-dxf2gcode")
    out.append(f"; date: {datetime.now().isoformat(timespec='seconds')}")
    for k, v in meta.items():
        out.append(ascii_comment(f"; {k}: {v}"))
    out.append(ascii_comment(f"; machine: {machine.name}  area: X0-{machine.x_max:g} Y0-{machine.y_max:g}  "
                             f"S max: {machine.s_max}"))
    if "kerf" not in meta:
        out.append(f"; kerf: {plan.kerf:.3f} mm")
    out.append(f"; pass_mode: {pass_mode}")
    if machine.unverified:
        out.append(ascii_comment("; WARNING unverified machine settings: " + ", ".join(machine.unverified)))
    out.append("; !!! Check the SVG preview before running. Test on scrap material first. !!!")
    out.append("; !!! Requires GRBL laser mode ($32=1) for M4 dynamic power. Never leave the machine unattended. !!!")
    out.append("G21 G90 G94")
    out.append("M5")
    out.append("S0")
    use_air = machine.air_assist_gcode
    if use_air:
        out.append("M9")
    out.append(f"G0 X{fmt(park[0])} Y{fmt(park[1])} S0")

    # (path, pass 番号, PassSetting) の実行列
    jobs = []
    if pass_mode == "path":
        for p in plan.paths:
            for k, ps in enumerate(p.settings.pass_settings()):
                jobs.append((p, k, ps))
    else:
        rounds = max((p.settings.passes for p in plan.paths), default=0)
        for k in range(rounds):
            for p in plan.paths:
                settings = p.settings.pass_settings()
                if k < len(settings):
                    jobs.append((p, k, settings[k]))

    air_on = False
    index = {id(p): i for i, p in enumerate(plan.paths)}
    warned_feed = set()
    for p, k, ps in jobs:
        i = index[id(p)]
        where = f"(layer '{p.layer}' pass {k + 1})"
        s = power_to_s(ps.power, machine.s_max, warnings, where)
        if s == 0:
            warnings.append(f"出力 0% のパスがあります {where}")
        feed = ps.feed
        if feed > max(machine.max_rate_x, machine.max_rate_y) and where not in warned_feed:
            warned_feed.add(where)
            warnings.append(f"送り速度 {feed} は機械の最大速度を超えています(GRBL が制限します) {where}")
        out.append(ascii_comment(
            f"; path {i + 1}/{len(plan.paths)} layer={p.layer} role={p.role} depth={p.depth} "
            f"part={p.part_id} pass {k + 1}/{p.settings.passes} power={ps.power:g}% feed={feed:g}"))
        x0, y0 = p.points[0]
        out.append(f"G0 X{fmt(x0)} Y{fmt(y0)} S0")
        if use_air:
            want = bool(p.settings.air_assist)
            if want and not air_on:
                out.append("M8")
            elif not want and air_on:
                out.append("M9")
            air_on = want
        out.append(f"M4 S{s}")
        first = True
        for x, y in p.points[1:]:
            if first:
                out.append(f"G1 X{fmt(x)} Y{fmt(y)} F{feed:g}")
                first = False
            else:
                out.append(f"G1 X{fmt(x)} Y{fmt(y)}")
        out.append("M5")

    if use_air and air_on:
        out.append("M9")
    if machine.return_home:
        out.append(f"G0 X{fmt(park[0])} Y{fmt(park[1])} S0")
    out.append("M5")
    text = "\n".join(out) + "\n"
    verify_gcode(text, machine)
    return GcodeResult(text=text, warnings=warnings, burns=len(jobs))


# --------------------------------------------------------------------------
# 3. パーサと検証
# --------------------------------------------------------------------------

_WORD = re.compile(r"([A-Za-z])\s*([-+]?(?:\d+\.?\d*|\.\d+))")


@dataclass
class Motion:
    kind: str          # "G0" | "G1"
    start: Point
    end: Point
    feed: float
    s: int
    laser_on: bool     # M4 中か
    line_no: int

    @property
    def burning(self) -> bool:
        return self.kind == "G1" and self.laser_on and self.s > 0


@dataclass
class ParsedGcode:
    motions: list[Motion]
    commands: list[tuple[int, str]]   # (行番号, コメントを除いた行)


def strip_comment(line: str) -> str:
    line = re.sub(r"\([^)]*\)", "", line)
    return line.split(";", 1)[0].strip()


def parse_gcode(text: str) -> ParsedGcode:
    """このツールが出す範囲の G-code を読む。未対応の G/M があれば GcodeSafetyError。"""
    motions: list[Motion] = []
    commands: list[tuple[int, str]] = []
    pos: Point = (0.0, 0.0)
    feed = 0.0
    s = 0
    laser_on = False
    motion_mode: str | None = None
    for no, raw in enumerate(text.splitlines(), 1):
        line = strip_comment(raw).upper()
        if not line:
            continue
        commands.append((no, line))
        words = _WORD.findall(line)
        leftover = _WORD.sub("", line).strip()
        if leftover:
            raise GcodeSafetyError(f"行 {no}: 解釈できない文字列 '{leftover}': {raw}")
        x = y = None
        this_motion = None
        for letter, val in words:
            v = float(val)
            if letter == "G":
                g = int(v) if v == int(v) else v
                if g not in ALLOWED_G:
                    raise GcodeSafetyError(f"行 {no}: 許可していない G コード G{val}: {raw}")
                if g in (0, 1):
                    this_motion = f"G{g}"
            elif letter == "M":
                m = int(v)
                if m not in ALLOWED_M or m != v:
                    raise GcodeSafetyError(f"行 {no}: 許可していない M コード M{val}(M3 は禁止。M4 を使う): {raw}")
                if m == 4:
                    laser_on = True
                elif m == 5:
                    laser_on = False
            elif letter == "S":
                s = int(round(v))
            elif letter == "F":
                feed = v
            elif letter == "X":
                x = v
            elif letter == "Y":
                y = v
            else:
                raise GcodeSafetyError(f"行 {no}: 許可していないワード {letter}{val}: {raw}")
        if this_motion:
            motion_mode = this_motion
        if x is not None or y is not None:
            if this_motion is None:
                raise GcodeSafetyError(f"行 {no}: 移動行には G0/G1 を明記すること: {raw}")
            new = (pos[0] if x is None else x, pos[1] if y is None else y)
            motions.append(Motion(motion_mode, pos, new, feed, s, laser_on, no))
            pos = new
    return ParsedGcode(motions, commands)


def verify_gcode(text: str, machine: Machine) -> ParsedGcode:
    """生成済み G-code の安全検証。違反があれば GcodeSafetyError / WorkAreaError。"""
    parsed = parse_gcode(text)
    cmds = parsed.commands
    if not cmds:
        raise GcodeSafetyError("G-code が空です")

    head = cmds[0][1].split()
    if not {"G21", "G90", "G94"} <= set(head):
        raise GcodeSafetyError("最初の命令が 'G21 G90 G94' ではありません")
    first_m5 = next((n for n, c in cmds if re.search(r"\bM5\b", c)), None)
    first_active = next((n for n, c in cmds if re.search(r"\bM4\b|\bG[01]\b", c)), None)
    if first_m5 is None or (first_active is not None and first_m5 > first_active):
        raise GcodeSafetyError("移動・発振より前に M5 がありません")
    if cmds[-1][1] != "M5":
        raise GcodeSafetyError(f"最後の命令が M5 ではありません: '{cmds[-1][1]}'")

    # G0 の行には必ず S0。発振中(M4 のまま)の G0 も禁止
    laser_on = False
    for no, c in cmds:
        if re.search(r"\bM4\b", c):
            laser_on = True
        if re.search(r"\bM5\b", c):
            laser_on = False
        if re.search(r"\bG0\b", c):
            if not re.search(r"\bS0(?:\.0*)?\b", c):
                raise GcodeSafetyError(f"行 {no}: G0 に S0 がありません: {c}")
            if laser_on:
                raise GcodeSafetyError(f"行 {no}: M4(発振)のまま G0 しています: {c}")
        for m in re.finditer(r"\bS(\d+(?:\.\d*)?)", c):
            if float(m.group(1)) > machine.s_max:
                raise GcodeSafetyError(f"行 {no}: S 値が最大 {machine.s_max} を超えています: {c}")

    for mo in parsed.motions:
        x, y = mo.end
        if x < 0 or y < 0 or x > machine.x_max or y > machine.y_max:
            raise WorkAreaError(f"行 {mo.line_no}: 加工エリア外の座標 X={x} Y={y}")
        if mo.kind == "G0" and mo.s != 0:
            raise GcodeSafetyError(f"行 {mo.line_no}: G0 中の S 値が 0 ではありません")
    return parsed
